---
  - include_vars: "{{ ansible_os_family }}.yml"
  - name: Deploy NTP on Ubuntu Servers
    apt: pkg=ntp state=latest
    when: ansible_os_family == 'Debian'
  - name: Deploy NTP for Red Hat Systems
    yum: pkg=ntp state=latest
    when: ansible_os_family == 'RedHat'
  - name: NTP Service Runs
    service: name={{ ntpserver }} state=started
