- hosts: vmware
  tasks:
    - name: Deploy pip for Ubuntu Servers
      apt: pkg=python-pip state=latest
      when: ansible_os_family == 'Debian'
    - name: Deploy pip for Red Hat Systems
      yum: pkg=python-pip state=latest
      when: ansible_os_family == 'RedHat'
    - name: Deploy the pysphere Python package
      pip: name=pysphere
    - name: Remove a specified VM
      vsphere_guest:
        vcenter_hostname: vcenter.devwidgets.io
        username: vmtrooper@devwidgets.io
        password: devopsrocks123
        guest: web server 01
        state: absent
        force: yes