# Create a new VM on an ESX server
# Returns changed = False when the VM already exists
# Returns changed = True and a adds ansible_facts from the new VM
# State will set the power status of a guest upon creation. Use powered_on to create and boot.
# Options ['state', 'vm_extra_config', 'vm_disk', 'vm_nic', 'vm_hardware', 'esxi'] are required together

- hosts: localhost
  gather_facts: false
  tasks:
    - raw: uname -a
    # - vsphere_guest:
    #     vcenter_hostname: "{{ ansible_ssh_host|default(inventory_hostname) }}"
    #     username: "{{ hostvars[inventory_hostname].ansible_ssh_user|quote }}"
    #     password: "{{ hostvars[inventory_hostname].ansible_ssh_pass|quote }}"
    #     guest: "My Guest"
    #     vmware_guest_facts: yes
    #   delegate_to: localhost
    - vsphere_guest:
        vcenter_hostname: vcenter.devwidgets.io
        username: admin@devwidgets.io
        password: devopsrocks123
        guest: newvm001
        state: powered_on
        vm_extra_config:
          vcpu.hotadd: yes
          mem.hotadd:  yes
          notes: This is a test VM
        vm_disk:
          disk1:
            size_gb: 5
            type: thin
            datastore: datastore1
        vm_nic:
          nic1:
            type: vmxnet3
            network: VM Network
            network_type: standard
        vm_hardware:
          memory_mb: 512
          num_cpus: 1
          osid: centos64Guest
          scsi: paravirtual
        esxi:
          datacenter: Production
          hostname: vsphere01.devwidgets.io